config/routes.rb
Spree::Core::Engine.add_routes do
  match 'product_customizations/price', to: 'product_customizations#price', via: [:get, :post]

  match 'customize/:product_id', to: 'products#customize', as: 'customize', via: [:get, :post]

  namespace :admin do

    # resources :configuration_exclusions
    resources :product_customization_types do
      resources :customizable_product_options do
        member do
          get :select
          post :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
    end

    resources :product_customization_types

    resources :ad_hoc_option_types do
      resources :ad_hoc_option_values do
        collection do
          post :update_positions
        end
      end
      member do
        get :remove
      end
    end

    delete '/ad_hoc_option_values/:id', to: "ad_hoc_option_values#destroy", as: :ad_hoc_option_value

    resources :ad_hoc_variant_exclusions

    resources :products do
      resources :option_types do
        member do
          get :select
          get :remove
          get :select_ad_hoc
          post :select_ad_hoc
        end
        collection do
          get :available
          get :selected
          get :available_ad_hoc
        end
      end
      resources :ad_hoc_option_types do
        collection do
          get :selected
        end
        member do
          get :add_option_value
        end
      end

      resources :ad_hoc_variant_exclusions

      resources :product_customization_types do
        member do
          get :select
          post :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
    end #products
  end # namespace :admin

  match 'admin/variant_configurations/:variant_id', to: 'admin/variant_configurations#configure', via: [:get, :post]
end

app/controllers/spree/admin/product_customization_types_controller.rb
module Spree
  class Admin::ProductCustomizationTypesController < Admin::ResourceController
    before_action :load_product, only: [:selected, :available, :remove]
    before_action :load_calculators, only: [:new, :edit]

    def load_calculators
      @calculators = ProductCustomizationType.calculators.sort_by(&:name)
    end

    def edit
      @product_customization_type= ProductCustomizationType.find(params[:id])

      # Is this an edit immediately after create?  If so, need to create
      # calculator-appropriate default options
      if @product_customization_type.customizable_product_options.empty?
        if !@product_customization_type.calculator.nil?

          opts = @product_customization_type.calculator.create_options
          @product_customization_type.customizable_product_options.concat opts if opts

          # for each mandatory input type
          #        @product_customization_type.calculator.required_fields.each_pair do |key, val|
          #          cpo= CustomizableProductOption.create(name: key, presentation: key.titleize, is_required: true,data_type: val)
          #          @product_customization_type.customizable_product_options << cpo
          #        end
        end
      end
    end

    def available
      set_available_product_customization_types
      render layout: false
    end

    def selected
      @product_customization_types = @product.product_customization_types
    end

    def remove
      @product.product_customization_types.delete(@product_customization_type)
      @product.save
      flash.notice = I18n.t("spree.notice_messages.product_customization_type_removed")
      redirect_to selected_admin_product_product_customization_types_url(@product)
    end


    # AJAX method for selecting an existing option type and associating with the current product
    def select
      @product = Product.friendly.find(params[:product_id])

      @product.product_customization_types << ProductCustomizationType.find(params[:id])
      @product.save
      @product_customization_types = @product.product_customization_types
      set_available_product_customization_types
    end

    protected

    def location_after_save
      if params[:action] == "update"
        admin_product_customization_types_url
      else
        edit_admin_product_customization_type_url(@product_customization_type)
      end
    end


    private
    def load_product
      @product = Product.friendly.find(params[:product_id])
    end

    def set_available_product_customization_types
      @available_product_customization_types = ProductCustomizationType.all.to_a
      selected_product_customization_types = []
      @product.product_customization_types.each do |pct|
        selected_product_customization_types << pct
      end
      @available_product_customization_types.delete_if {|pct| selected_product_customization_types.include? pct}
    end
  end
end

app/views/spree/admin/product_customization_types/_available.html.erb
<h4><%= Spree.t("add_product_customization_types") %></h4>

<% if @available_product_customization_types.any? %>
  <table class="table" id='available_product_customization_types' data-hook>
    <thead>
      <tr data-hook="available_product_customization_types_header">
        <th><%= Spree.t("name") %></th>
        <th><%= Spree.t("presentation") %></th>
        <th><%= Spree.t("description") %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @available_product_customization_types.each do |available_product_customization_type| %>
        <tr id="<%= spree_dom_id(available_product_customization_type) %>">
          <td class="name"><%= available_product_customization_type.name %></td>
          <td class='presentation'><%= available_product_customization_type.presentation %></td>
          <td class='description'><%= available_product_customization_type.description %></td>
          <td class="actions actions-1 text-right">
            <%= link_to_with_icon 'add', '', url_for(
              controller: "admin/product_customization_types",
              id: available_product_customization_type,
              product_id: @product.slug,
              action: "select",
              product_customization_type_id:  available_product_customization_type), remote: true, class: 'btn btn-success btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::ProductCustomization)) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_product_customization_type_url %>!
  </div>
<% end %>

app/views/spree/admin/product_customization_types/_customizable_product_option_fields.html.erb
<tr class="customization_value type fields" id="spree_dom_id(f.object)%>  %>" data-hook="customization_value">
  <% if editable %>
    <td><%= f.text_field :name, class: "form-control" %></td>
  <% else %>
    <td><%= f.text_field :name, readonly: true, disabled: true, class: "form-control" %></td>
  <% end %>
  <td><%= f.text_field :presentation, class: "form-control" %></td>
  <td><%= f.text_field :description, class: "form-control" %></td>
  <% if editable %>
    <td class="actions actions-<1 text-center">
      <%# TODO fix this link %>
      <%= link_to_with_icon 'delete', '', remove_admin_product_product_customization_type_path(f), class: 'btn btn-danger btn-sm' %>
    </td>
  <% else %>
    <td class="actions actions-0 text-center">
    </td>
  <% end %>
</tr>

app/views/spree/admin/product_customization_types/_form.html.erb
<div data-hook="admin_product_customization_type_form_fields" class="row">
  <div class="col-md-4">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name,Spree.t(:name) %> <span class="required">*</span>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div class="col-md-4">
    <%= f.field_container :presentation, class: ['form-group'] do %>
      <%= f.label :presentation,Spree.t(:presentation) %> <span class="required">*</span>
      <%= f.text_field :presentation, class: "form-control" %>
      <%= f.error_message_on :presentation %>
    <% end %>
  </div>

  <div class="col-md-4">
    <%= f.field_container :description, class: ['form-group'] do %>
      <%= f.label :description,Spree.t(:description) %>
      <%= f.text_field :description, class: "form-control" %>
      <%= f.error_message_on :description %>
    <% end %>
  </div>

</div>
<%= render "spree/admin/shared/calculator_fields", f: f %>

app/views/spree/admin/product_customization_types/_selected.html.erb
<% if @product_customization_types.any? %>
  <table class="table" id='product_customization_types' data-hook>
    <thead>
      <tr data-hook="product_customization_types_header">
        <th><%= Spree.t("name") %></th>
        <th><%= Spree.t("presentation") %></th>
        <th><%= Spree.t("description") %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @product_customization_types.each do |product_customization_type| %>
        <tr id="<%= spree_dom_id(product_customization_type) %>">
          <td class='name'><%= product_customization_type.name %></td>
          <td class='presentation'><%= product_customization_type.presentation %></td>
          <td class='description'><%= product_customization_type.description %></td>
          <td class="actions actions-1 text-right">
            <%= link_to_with_icon 'delete', '', remove_admin_product_product_customization_type_url(@product, product_customization_type), class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::ProductCustomization)) %>,
    <%= link_to Spree.t(:add_one), spree.available_admin_product_product_customization_types_url(@product), remote: :true %>!
  </div>
<% end %>

<div id="customization-types"></div>
  <span id="new_ct_link">
    <%= link_to_with_icon 'add', Spree.t("add_product_customization_type"), available_admin_product_product_customization_types_url(@product), remote: :true %>
  </span>

app/views/spree/admin/product_customization_types/available.js.erb
$("#customization-types").html("<%= raw escape_javascript(render('available')) %>");
$("#new_ct_link").hide();

app/views/spree/admin/product_customization_types/edit.html.erb
<%= content_for :head do %>
  <%= javascript_tag do %>
    Spree.ready(function () {
      $('form').validate();
    });
  <% end %>
<% end %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::ProductCustomizationType.model_name.human) %> <span class="green">"<%= @product_customization_type.name %>"</span>
<% end %>

<% if @product_customization_type.calculator.type == "Spree::Calculator::NoCharge" %>
  <% content_for :page_actions do %>
    <span id="customizable_product_options_value" data-hook>
      <%= button_link_to Spree.t(:add_option_value), "javascript:;", icon: 'add', :'data-target' => "tbody#customizable_product_options", class: 'btn-success spree_add_fields'  %>
    </span>
  <% end %>
<% end %>

<%= render 'spree/admin/shared/error_messages', target: @product_customization_type %>

<%= form_for(@product_customization_type, url: admin_product_customization_type_url(@product_customization_type), html: { method: :put }) do |f| %>
  <fieldset>
    <%= render partial: "form", locals: { f: f } %>

    <h3><%= Spree.t("customizable_product_options") %></h3>
    <table class="table index" id='customizable_product_options' data-hook>
      <thead>
        <tr data-hook="customizable_product_options_header">
          <th><%= Spree.t("name") %><span class="required">*</span></th>
          <th><%= Spree.t("presentation") %><span class="required">*</span></th>
          <th><%= Spree.t("description") %></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody id="customizable_product_options">
        <% if @product_customization_type.calculator.type == "Spree::Calculator::NoCharge" %>
          <%= f.fields_for :customizable_product_options do |customizable_form| %>
            <%= render partial: "customizable_product_option_fields", locals: { f: customizable_form, editable: true } %>
          <% end %>
        <% else %>
          <%= f.fields_for :customizable_product_options do |customizable_form| %>
            <%= render partial: "customizable_product_option_fields", locals: { f: customizable_form, editable: false } %>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/product_customization_types/index.html.erb
<% content_for(:page_title, Spree.t("product_customization_types")) %>
<% content_for(:page_actions) do %>
  <%= button_link_to Spree.t("new_product_customization_type"), spree.new_admin_product_customization_type_url, class: 'btn-success', icon: 'add', id: 'new_product_customization_type_link' %>
<% end %>

<% if @product_customization_types.any? %>
  <table class="table" id='product_customization_types' data-hook>
    <thead>
      <tr data-hook="product_customization_types_header">
        <th><%= Spree.t("name") %></th>
        <th><%= Spree.t("presentation") %></th>
        <th><%= Spree.t("description") %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @product_customization_types.each do |product_customization_type| %>
        <tr id="<%= spree_dom_id(product_customization_type) %>">
          <td class='name'><%= product_customization_type.name %></td>
          <td class='presentation'><%= product_customization_type.presentation %></td>
          <td class='description'><%= product_customization_type.description %></td>
          <td class="actions actions-2 text-right">
            <%= link_to_edit(product_customization_type, no_text: true, class: 'admin_edit_product_customization_type') %>
            <%= link_to_delete(product_customization_type, no_text: true) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::ProductCustomization)) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_product_customization_type_url %>!
  </div>
<% end %>

app/views/spree/admin/product_customization_types/new.html.erb
<% content_for :page_title do %>
  <%=Spree.t(:new_product_customization_type) %>
<% end %>

<%= render 'spree/admin/shared/error_messages', target: @product_customization_type  %>

<%= form_for(@product_customization_type, url: admin_product_customization_types_url) do |f| %>
  <fieldset>
    <%= render partial: "form", locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/product_customization_types/select.js.erb
$("#selected-customization-types").html("<%= raw escape_javascript(render 'selected') %>");
$("#customization-types").html("");
$("#new_ct_link").show();

app/views/spree/admin/product_customization_types/selected.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: {current: "Product Customization Types"} %>

<div id="selected-customization-types">
  <%= render 'selected' %>
</div>