config/routes.rb
Spree::Core::Engine.add_routes do
  match 'product_customizations/price', to: 'product_customizations#price', via: [:get, :post]

  match 'customize/:product_id', to: 'products#customize', as: 'customize', via: [:get, :post]

  namespace :admin do

    # resources :configuration_exclusions
    resources :product_customization_types do
      resources :customizable_product_options do
        member do
          get :select
          post :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
    end

    resources :product_customization_types

    resources :ad_hoc_option_types do
      resources :ad_hoc_option_values do
        collection do
          post :update_positions
        end
      end
      member do
        get :remove
      end
    end

    delete '/ad_hoc_option_values/:id', to: "ad_hoc_option_values#destroy", as: :ad_hoc_option_value

    resources :ad_hoc_variant_exclusions

    resources :products do
      resources :option_types do
        member do
          get :select
          get :remove
          get :select_ad_hoc
          post :select_ad_hoc
        end
        collection do
          get :available
          get :selected
          get :available_ad_hoc
        end
      end
      resources :ad_hoc_option_types do
        collection do
          get :selected
        end
        member do
          get :add_option_value
        end
      end

      resources :ad_hoc_variant_exclusions

      resources :product_customization_types do
        member do
          get :select
          post :select
          get :remove
        end
        collection do
          get :available
          get :selected
        end
      end
    end #products
  end # namespace :admin

  match 'admin/variant_configurations/:variant_id', to: 'admin/variant_configurations#configure', via: [:get, :post]
end

app/models/spree/ad_hoc_option_type.rb
module Spree
  class AdHocOptionType < ActiveRecord::Base
    belongs_to :option_type
    belongs_to :product
    has_many :ad_hoc_option_values, dependent: :destroy
    alias :option_values :ad_hoc_option_values

    accepts_nested_attributes_for :ad_hoc_option_values, allow_destroy: true

    # currently no controller for normal users present
    #attr_accessible :is_required, :ad_hoc_option_values_attributes, :product_id, :option_type_id, :position

    default_scope -> { order(:position) }

    # price_modifier_type
    # is_required
    def has_price_modifier?
      !(price_modifier_type.nil? || price_modifier_type.downcase=~/none/)
    end

    def name
      option_type.name
    end

    def presentation
      option_type.presentation
    end
  end
end

app/models/spree/ad_hoc_option_value.rb
# I chose to create a new class instead of modifying the option_value class to include a price_modifier and fk back to ad_hoc_option_type
module Spree
  class AdHocOptionValue < ActiveRecord::Base
    belongs_to :ad_hoc_option_type
    belongs_to :option_value
    has_many :excluded_ad_hoc_option_values, dependent: :destroy

    # currently no controller for normal users present
    #attr_accessible :price_modifier, :ad_hoc_option_type_id, :option_value_id, :selected, :cost_price_modifier

    # this opens up a can of worms..deleting option values and having historical data still intact...ugh...what to do?...add 'deleted_at' somewhere along the chain?
    # has_many :ad_hoc_option_values_line_items, dependent: :destroy

    # price_modifier
    alias :option_type :ad_hoc_option_type
    acts_as_list scope: :ad_hoc_option_type
    default_scope -> {order("position asc")}

    delegate :name, to: :option_value
    delegate :presentation, to: :option_value

    def cost_price
      cost_price_modifier || price_modifier || 0
    end
  end
end

app/models/spree/ad_hoc_option_values_line_item.rb
module Spree
  class AdHocOptionValuesLineItem  < ActiveRecord::Base
    belongs_to :ad_hoc_option_value
    belongs_to :line_item
  end
end

app/models/spree/ad_hoc_variant_exclusion.rb
module Spree
  class AdHocVariantExclusion < ActiveRecord::Base
    belongs_to :product
    has_many :excluded_ad_hoc_option_values, dependent: :destroy
  end
end

app/models/spree/calculator/amount_times_constant.rb
module Spree
  class Calculator::AmountTimesConstant < Calculator
    preference :multiplier, :decimal

    preference :min_amount, :integer, default: 0
    preference :max_amount, :integer, default: 100

    #attr_accessible :preferred_multiplier, :preferred_min_amount, :preferred_max_amount

    def self.description
      "Amount Times Constant Calculator"
    end

    def self.register
      super
      ProductCustomizationType.register_calculator(self)
    end

    def create_options
      # This calculator knows that it needs one CustomizableOption named amount
      [
       CustomizableProductOption.create(name: "amount", presentation: "Amount")
      ]
    end

    def compute(product_customization, variant=nil)
      return 0 unless valid_configuration? product_customization

      # expecting only one CustomizedProductOption
      opt = product_customization.customized_product_options.detect {|cpo| cpo.customizable_product_option.name == "amount" } rescue 0.0
      opt.value.to_i * preferred_multiplier
    end

    def valid_configuration?(product_customization)
      true
    end
  end
end

app/models/spree/calculator/customization_image.rb
require_dependency 'spree/calculator'

module Spree
  class Calculator::CustomizationImage < Calculator
    preference :price, :decimal
    #attr_accessible :preferred_price, :decimal

    def self.description
      "Product Customization Image Calculator"
    end

    def self.register
      super
      ProductCustomizationType.register_calculator(self)
    end

    def create_options
      # This calculator knows that it needs one CustomizableOption named customization_image
      [
       CustomizableProductOption.create(name: "customization_image", presentation: "Customization Image")
      ]
    end

    def compute(product_customization,variant=nil)
      return 0 unless valid_configuration? product_customization

      # expecting only one CustomizedProductOption
      opt = product_customization.customized_product_options.detect {|cpo| cpo.customizable_product_option.name == "customization_image" } rescue ''

      if opt && opt.customization_image?
        preferred_price
      else
        0.00   # no image was uploaded
      end
    end

    def valid_configuration?(product_customization)
      true
    end
  end
end

app/models/spree/calculator/engraving.rb
require_dependency 'spree/calculator'

module Spree
  class Calculator::Engraving < Calculator
    preference :price_per_letter, :decimal
    #attr_accessible :preferred_price_per_letter

    def self.description
      "Engraving Calculator"
    end

    def self.register
      super
      ProductCustomizationType.register_calculator(self)
    end

    def create_options
      # This calculator knows that it needs one CustomizableOption named inscription
      [
       CustomizableProductOption.create(name: "inscription", presentation: "Inscription")
      ]
    end

    def compute(product_customization, variant=nil)
      return 0 unless valid_configuration? product_customization

      # expecting only one CustomizedProductOption
      opt = product_customization.customized_product_options.detect {|cpo| cpo.customizable_product_option.name == "inscription" } rescue ''
      opt.value.length * (preferred_price_per_letter || 0)
    end

    def valid_configuration?(product_customization)
      true
    end
  end
end

app/models/spree/calculator/no_charge.rb
require_dependency 'spree/calculator'

module Spree
  class Calculator::NoCharge < Calculator
    def self.description
      "This customization has no charge"
    end

    def self.register
      super
      ProductCustomizationType.register_calculator(self)
    end

    def create_options
      # This calculator knows that it needs one CustomizableOption named amount
      [
      ]
    end

    def compute(product_customization, variant=nil)
      return 0
    end

    def valid_configuration?(product_customization)
      true
    end
  end
end

app/models/spree/calculator/product_area.rb
module Spree
  class Calculator::ProductArea < Calculator
    preference :multiplier, :decimal

    preference :min_pricing_area, :integer  # the minimum size we'll use for pricing (we might sell you a 4x4, but we'll charge u for a 10x10

    preference :min_width, :integer, default: 0
    preference :max_width, :integer, default: 100

    preference :min_height, :integer, default: 0
    preference :max_height, :integer, default: 100

    #attr_accessible :preferred_multiplier, :preferred_min_pricing_area, :preferred_min_width, :preferred_max_width,:preferred_min_height, :preferred_max_height

    # preference :min_area, :integer  # the minimum sized frame we'll sell

    # these can be reflected in the custom partials?
    #  preference :measurement_units, :string, default: 'inches'
    #  preference :granularity, :string, default: 'eighths'

    def self.description
      "Product Area Calculator"
    end

    def self.register
      super
      ProductCustomizationType.register_calculator(self)
    end

    def create_options
      # This calculator knows that it needs two CustomizableOptions, width & height
      [
       CustomizableProductOption.create(name: "width", presentation: "Width"),
       CustomizableProductOption.create(name: "height", presentation: "Height")
      ]
    end

    # as object we always get line items, as calculable we have Coupon, ShippingMethod
    def compute(product_customization, variant=nil)
      return 0 unless valid_configuration? product_customization

      width,height = get_option(product_customization, "width"), get_option(product_customization, "height")

      # here's the custom logic for this calculator:  min total width + height = 20.
      [(width.value.to_f * height.value.to_f), (preferred_min_pricing_area || 0)].max * preferred_multiplier
    end

    def valid_configuration?(product_customization)
      # expecting exactly two CustomizedProductOptions

      all_opts = product_customization.customized_product_options.map {|cpo| cpo.customizable_product_option.name }

      # do we have the necessary inputs?
      has_inputs = all_opts.include?("width") && all_opts.include?("height")

      # do the inputs meet the criteria?
      width,height = get_option(product_customization, "width"), get_option(product_customization, "height")

      #    return has_inputs && width && height && (width.value.to_f * height.value.to_f) >= preferred_min_area

      #    rescue false
      return true
    end


    private
    def get_option(product_customization, name)
      product_customization.customized_product_options.detect {|cpo| cpo.customizable_product_option.name == name }
    end

  end
end

app/models/spree/customizable_product_option.rb
module Spree
  class CustomizableProductOption < ActiveRecord::Base
    belongs_to :product_customization_type
    delegate :calculator, to: :product_customization_type
    #attr_accessible :name, :presentation, :description, :product_customization_type_id
  end
end

app/models/spree/customized_product_option.rb
module Spree
  # in populate, params[:customization] contains all the fields supplied by
  # the customization_type_view. Those values are saved in this class
  class CustomizedProductOption < ActiveRecord::Base
    belongs_to :product_customization
    belongs_to :customizable_product_option

    has_attached_file :customization_image,
                      styles: {
                        thumb: '50x50^'
                      },
                      convert_options: {
                        thumb: " -gravity center -crop '50x50+0+0'",
                      }

    def empty?
      value.empty? && !customization_image?
    end
  end
end

app/models/spree/excluded_ad_hoc_option_value.rb
module Spree
  class ExcludedAdHocOptionValue < ActiveRecord::Base
    belongs_to :ad_hoc_variant_exclusion
    belongs_to :ad_hoc_option_value
    
    #attr_accessible :ad_hoc_variant_exclusion, :ad_hoc_option_value_id
  end
end

app/models/spree/line_item_decorator.rb
module Spree
  LineItem.class_eval do
    has_many :ad_hoc_option_values_line_items, dependent: :destroy
    has_many :ad_hoc_option_values, through: :ad_hoc_option_values_line_items
    has_many :product_customizations, dependent: :destroy

    def options_text
      str = Array.new
      unless self.ad_hoc_option_values.empty?

        #TODO: group multi-select options (e.g. toppings)
        str << self.ad_hoc_option_values.each { |pov|
          "#{pov.option_value.option_type.presentation} = #{pov.option_value.presentation}"
        }.join(',')
      end # unless empty?

      unless self.product_customizations.empty?
        self.product_customizations.each do |customization|
          price_adjustment = (customization.price == 0) ? "" : " (#{Spree::Money.new(customization.price).to_s})"
          str << "#{customization.product_customization_type.presentation}#{price_adjustment}"
          customization.customized_product_options.each do |option|
            next if option.empty?

            if option.customization_image?
              str << "#{option.customizable_product_option.presentation} = #{File.basename option.customization_image.url}"
            else
              str << "#{option.customizable_product_option.presentation} = #{option.value}"
            end
          end # each option
        end # each customization
      end # unless empty?

      str.join('\n')
    end

    def cost_price
      (variant.cost_price || 0) + ad_hoc_option_values.map(&:cost_price).inject(0, :+)
    end

    def cost_money
      Spree::Money.new(cost_price, currency: currency)
    end
  end
end

app/models/spree/option_type_decorator.rb
module Spree
  OptionType.class_eval do
    has_many :ad_hoc_option_types, dependent: :destroy
  end
end

app/models/spree/option_value_decorator.rb
module Spree
  OptionValue.class_eval do
    has_many :ad_hoc_option_values, dependent: :destroy
  end
end

app/models/spree/order_contents_decorator.rb
module Spree
  OrderContents.class_eval do

    private
    #this whole thing needs a refactor!

    def add_to_line_item(variant, quantity, options = {})
      line_item = grab_line_item_by_variant(variant, false, options)
      if line_item
        line_item.quantity += quantity.to_i
        line_item.currency = currency unless currency.nil?
      else
        options_params = options.is_a?(ActionController::Parameters) ? options : ActionController::Parameters.new(options.to_h)
        opts = options_params.
          permit(PermittedAttributes.line_item_attributes).to_h.
          merge(currency: order.currency)

        line_item = order.line_items.new(quantity: quantity, variant: variant, options: opts)

        product_customizations_values = options[:product_customizations] || []
        line_item.product_customizations = product_customizations_values
        product_customizations_values.each { |product_customization| product_customization.line_item = line_item }
        product_customizations_values.map(&:save) # it is now safe to save the customizations we built

        # find, and add the configurations, if any.  these have not been fetched from the db yet.              line_items.first.variant_id
        # we postponed it (performance reasons) until we actually know we needed them
        ad_hoc_option_value_ids = ( !!options[:ad_hoc_option_values] ? options[:ad_hoc_option_values] : [] )
        product_option_values = ad_hoc_option_value_ids.map do |cid|
          AdHocOptionValue.find(cid) if cid.present?
        end.compact
        line_item.ad_hoc_option_values = product_option_values

        offset_price = product_option_values.map(&:price_modifier).compact.sum + product_customizations_values.map {|product_customization| product_customization.price(variant)}.compact.sum

        if currency
          line_item.currency = currency unless currency.nil?
          line_item.price    = variant.price_in(currency).amount + offset_price
        else
          line_item.price    = variant.price + offset_price
        end
      end
      line_item.target_shipment = options[:shipment] if options.has_key? :shipment
      line_item.save!
      line_item
    end
  end
end

app/models/spree/product_customization.rb
module Spree
  class ProductCustomization < ActiveRecord::Base
    belongs_to :product_customization_type
    belongs_to :line_item
    has_many :customized_product_options, dependent: :destroy
    #attr_accessible :product_customization_type_id, :line_item_id
    # TODO: Jeff, add 'required'

    # price might depend on something contained in the variant (like product property value)a
    def price(variant=nil)
      amount = product_customization_type.calculator.compute(self, variant)
    end

    def calculator
      product_customization_type.calculator
    end
  end
end

app/models/spree/product_customization_type.rb
module Spree
  class ProductCustomizationType < ActiveRecord::Base
    include Spree::CalculatedAdjustments
    has_and_belongs_to_many :products
    has_many :customizable_product_options, dependent: :destroy
    accepts_nested_attributes_for :customizable_product_options, allow_destroy: true
    #attr_accessible :name, :presentation, :description, :customizable_product_options_attributes
    validates :name, :presentation, presence: true
  end
end

app/views/spree/products/_ad_hoc_option_types.html.erb
<% if !!@product.ad_hoc_option_types && @product.ad_hoc_option_types.present? %>
  <% lookup = ActionView::LookupContext.new(ActionController::Base.view_paths, {formats: [:html]}) %>

  <div id="ad_hoc_options">
    <div class='col-sm-12'>
      <h3 class="product-section-title"><%= Spree.t(:select_variant_options) %></h3>
      <% if @product.ad_hoc_variant_exclusions.present? %>
        <h6 id="not_all_available">
          <%= Spree.t(:not_all_combinations_available) %>
        </h6>
      <% end %>
    </div>
    <ul class="list-group list-unstyled">
      <% @product.ad_hoc_option_types.each do |ad_hoc_option_type| %>
        <%# ugly logic %>
        <% option_type = ad_hoc_option_type.option_type %>
        <% class_str = 'ad-hoc-option-select' %>
        <% class_str += ' required' if ad_hoc_option_type.is_required %>
        <% class_str += ' ad_hoc' if @product.ad_hoc_variant_exclusions.present? %>
        <%# render a custom partial based on the option type name? %>
        <% partial_name = "spree/products/ad_hoc_options/#{option_type.name.gsub(/(-)|(\s)/,"_").downcase}" %>

        <% if lookup.exists?(partial_name, nil, true) %>
          <div class='col-sm-<%= Spree.t(:variant_col_size) %>'>
          <%= render partial: partial_name, locals: {option_type: ad_hoc_option_type, class_str: class_str} %>
          </div>
        <% else %>
          <li>
            <% select_opts = { class: "#{class_str} form-control" } %>
            <% select_opts[:prompt] = 'None' if ad_hoc_option_type.option_values.size > 1 && ad_hoc_option_type.option_values.none? {|option_value| option_value.selected? }%>
            <% selected_option_value = ad_hoc_option_type.option_values.detect {|option_value| option_value.selected? } %>
            <div class="col-md-<%= Spree.t(:variant_col_size) %> form-group">
              <h5 class='presentation-for-ad-hoc-option-value'><%= option_type.presentation %>: </h5>
              <div class='form-for-ad-hoc-option-value'>
                <%= select_tag "ad_hoc_option_values[#{ad_hoc_option_type.id}]",options_for_select(ad_hoc_option_value_options(ad_hoc_option_type.option_values), selected_option_value.present? ? selected_option_value.id.to_s : nil), select_opts %>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/spree/products/_content_for_body_javascript.html.erb
<%= content_for :flexi_variants_body_js do %>
  <% if @product.ad_hoc_variant_exclusions.present? %>
    <%= javascript_tag do %>
      var exclusions = [
        <% @product.ad_hoc_variant_exclusions.each do |ad_hoc_variant_exclusion| %>
          {
            <% @product.ad_hoc_option_types.each do |ad_hoc_option_type| %>
              <% option_value = ad_hoc_variant_exclusion.excluded_ad_hoc_option_values.detect { |excluded_option_value| excluded_option_value.ad_hoc_option_value.option_type == ad_hoc_option_type } %>
              <% option_value_string = option_value.nil? ? "*" : option_value.ad_hoc_option_value.id.to_s %>
              <%= raw "'ad_hoc_option_values_#{ad_hoc_option_type.id}':'#{option_value_string}'" %>
              <% unless ad_hoc_option_type == @product.ad_hoc_option_types.last %>
                ,
              <% end %>
            <% end %>
          }
          <% unless ad_hoc_variant_exclusion == @product.ad_hoc_variant_exclusions.last %>
            ,
          <% end %>
        <% end %>
      ];
    <% end %>
    <%= javascript_include_tag 'spree/frontend/spree_flexi_variants_exclusions' %>
  <% end %>
<% end %>

app/views/spree/products/_customizations.html.erb
<% if !!@product.product_customization_types && @product.product_customization_types.present? %>
  <%# for finding optional partials %>
  <% lookup = ActionView::LookupContext.new(ActionController::Base.view_paths, {formats: [:html]}) %>

  <div id="product-customizations">
    <div class= 'col-sm-12'>
      <h3 class="product-section-title"><%=Spree.t(:customizations) %></h3>
    </div>
    <ul class="list-group list-unstyled">
      <% @product.product_customization_types.group_by{ |x| calculator_name(x) }.each do |product_customization_grouped_by_calc_type| %>
        <% product_clac_name, product_customization_type_group = product_customization_grouped_by_calc_type %>
        <div class='col-sm-12'>
          <legend><%= product_customization_type_group.first.presentation %></legend>
        </div>
        <% product_customization_type_group.each do |product_customization_type| %>
          <%# render a custom partial based on the customization name? %>
          <% param_prefix = "product_customizations[#{product_customization_type.id}]" %>
          <% partial_name = "spree/products/customizations/customization_type/#{product_customization_type.name}" %>
          <% if lookup.exists?(partial_name,nil,true) %>
            <%= render partial: partial_name, locals: {product_customization_type: product_customization_type, param_prefix: param_prefix} %>
          <% else %>
            <% partial_name = "spree/products/customizations/calculator_type/#{product_clac_name}" %>
            <% if lookup.exists?(partial_name,nil,true) %>
              <%= render partial: partial_name, locals: {product_customization_type: product_customization_type, param_prefix: param_prefix} %>
            <% else %>
              <li>
                <div class="col-md-<%= Spree.t(:variant_col_size) %> form-group">
                  <p><%= product_customization_type.description  %></p>
                  <% product_customization_type.customizable_product_options.each_with_index do |customizable_product_option, index| %>
                    <h5 class="presentation-for-customizable-product-option">
                      <%= customizable_product_option.presentation %>
                    </h5>
                    <div class="form-for-customizable-product-option <%= "customization_option_#{index}" %>">
                      <%= text_field_tag "#{param_prefix}[#{customizable_product_option.id}]","", class: "customization form-control", placeholder:  customizable_product_option.description%>
                    </div>
                  <% end # options.each %>
                </div>
              </li>
            <% end %> <%# lookup.exists? %>
          <% end %> <%# lookup.exists? %>
        <% end %> <%# each product_customization_type %>
        <div class='col-sm-12'></div>
      <% end %> <%# each product_customization_grouped_by_calc_type %>
    </ul>
  </div> <!-- product-customizations -->
<% end %>

app/views/spree/products/_optional_customization_step_for_products_show.html.erb
<%# TODO edit this page to match styles %>
<% if SpreeFlexiVariants::Config[:use_separate_customizations_page] %>
  <% if @product.price %>
    <div data-hook="product_price" class="columns five <% if !@product.has_variants? %> alpha <% else %> omega <% end %>">

      <div id="product-price">
        <h6 class="product-section-title"><%= Spree.t(:price) %></h6>
        <div><span class="price selling" itemprop="price"><%= number_to_currency @product.price %></span></div>
      </div>
      <%= link_to "Customize", customize_path(@product) %>
    </div>
  <% end %>
<% else %>
  <div id="cart-form" data-hook="cart_form">
    <%= render partial: 'cart_form' %>
  </div>
<% end %>

app/views/spree/products/_pricing.html.erb
<% if SpreeFlexiVariants::Config[:use_javascript_pricing_updates] %>
  <%= content_for :flexi_variants_body_js do %>
    <%# didn't use javascript_tag here so we don't confuse deface %>
    <script type="text/javascript">
      //<![CDATA[
      // First I need to set up a mapping for the variants on the screen so I can easily grab their prices
      var variant_price_map = {};

      <% if @product.has_variants? %>
        <% @product.variants.active.each_with_index do |variant, index| %>
          variant_price_map[<%= variant.id %>] = <%= variant.price %>;
        <% end %>
      <% end %>

      // we start off the page w/ a known base price, a known set of
      // possible configurations (ad_hoc_option_values), and no customizations

      // 'updatePrice()' takes the base price + current 'configuration' adjustments + 'customization' adjustments

      var base_price = <%= @product.price %>;

      // keep track of ad_hoc adjustments
      var price_modifier_map = {};

      <% @product.ad_hoc_option_types.each do |product_option_type| %>
        <% product_option_type.option_values.each do |product_option_value| %>
          price_modifier_map[<%= product_option_value.id %>] = <%= product_option_value.price_modifier %>;
        <% end %>
      <% end %>


      var delay = (function(){
        var timer = 0;
        return function(callback, ms){
          clearTimeout (timer);
          timer = setTimeout(callback, ms);
        };
      })();

      Spree.ready(function() {

        // watch for variant changes
        $("#product-variants input[type='radio']").change(function() {
          updatePrice();
        });

        // 'watch' our configurations
        $('.ad-hoc-option-select').change(function() {

          // get _every_ option drop down and recalculate product price
          // do this immediately, since we are not waiting on the results of the exlusions post
          updatePrice();
        });

        if ($('.ad-hoc-option-select').length) {
          updatePrice(); // set the initial price
        }
      }); // ready

    // stolen from http://stackoverflow.com/questions/18082/validate-numbers-in-javascript-isnumeric
    function isNumeric(input) {
      return (input - 0) == input && input.length > 0;
    }

    function compute_variant_price_diff(base_price) {
      var variant_price = 0;

      $("#product-variants input[type='radio']:checked").each (function() {
        variant_price = variant_price_map[$(this).val()];
      });

      <% if @product.has_variants? %>
        return variant_price - base_price;
      <% else %>
        return variant_price;  // don't return a negative number if we don't have any variants
      <% end %>

    }

    function compute_configuration_price() {
      var configuration_price = 0;

      // for selects or checkboxes
      $("select.ad-hoc-option-select, input:checked.ad-hoc-option-select").each(function() {
        // the prompt: 'None' in the select tag yields an empty string, which I can't use in the price calcuation
        var val = $(this).val();

        // now in case we are a multiple select, de-array
        if ($.isArray(val)) {
          $.each(val, function(index, value) {
            if (isNumeric(value)) {
              configuration_price += price_modifier_map[value];
            }
          });
        } else {
          if (isNumeric(val)) {
            configuration_price += price_modifier_map[val];
          }
        }
      });
      return configuration_price;
    }

    function compute_customization_price() {
      var price = 0;

      // for selects or checkboxes
      $(".customization_price").each(function() {
        var val = $(this).val();

        if (isNumeric(val)) {
          price += parseFloat(val);
        }
      });

      return price;
    }

    function updatePrice() {
      var cur_variant_price_diff = compute_variant_price_diff(base_price);
      var cur_configuration_price = compute_configuration_price();
      var cur_customization_price = compute_customization_price();
      var cur_price = base_price + cur_variant_price_diff + cur_configuration_price + cur_customization_price;

      var region = $.formatCurrency.getRegionFromCurrency("<%= @product.currency %>");
      $('.price.selling').text(cur_price.toFixed(2)).formatCurrency({region: region});
    }

    //]]>
    </script>
  <% end %>
<%# end if SpreeFlexiVariants::Config[:use_javascript_pricing_updates] %>
<% end %>

app/views/spree/products/customize.html.erb
<% @body_id = 'product-details' %>
<h1><%= Spree.t('Customize') %> <%= accurate_title %></h1>

<div id="product-images" data-hook="product_images">
  <div id="main-image">
    <%= render 'image' %>
  </div>
</div>

<div id="cart-form" data-hook="cart_form">
  <%= render 'cart_form' %>
</div>